spring.datasource.url=jdbc:postgresql://localhost:5432/kundenverwaltung
spring.datasource.username=postgres
spring.datasource.password=PostgresSuperUser18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true